from django.test import TestCase
from rest_framework.test import APIClient
from rest_framework import status
from .models import Buyer, Supplier, AdminUser, Category, Product


class BuyerRegistrationTest(TestCase):
    def setUp(self):
        self.client = APIClient()

    def test_buyer_register(self):
        res = self.client.post('/api/buyers/', {
            'name': 'Test Buyer', 'email': 'buyer@test.com',
            'phone': '9876543210', 'password': 'test1234',
        }, format='json')
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)

    def test_buyer_login(self):
        buyer = Buyer(name='B', email='b@b.com', phone='1234567890')
        buyer.set_password('pass1234')
        buyer.save()

        res = self.client.post('/api/login/', {'email': 'b@b.com', 'password': 'pass1234'}, format='json')
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        self.assertIn('access', res.data)
        self.assertEqual(res.data['role'], 'buyer')

    def test_buyer_wrong_password(self):
        buyer = Buyer(name='B', email='bwrong@b.com', phone='1234567890')
        buyer.set_password('correct')
        buyer.save()

        res = self.client.post('/api/login/', {'email': 'bwrong@b.com', 'password': 'wrong'}, format='json')
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)


class SupplierRegistrationTest(TestCase):
    def setUp(self):
        self.client = APIClient()

    def test_supplier_register(self):
        res = self.client.post('/api/suppliers/', {
            'name': 'Test Supplier', 'email': 'sup@test.com',
            'phone': '9876543210', 'shop_name': 'My Shop', 'password': 'test1234',
        }, format='json')
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)


class ProductTest(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.supplier = Supplier(
            name='Sup', email='s@s.com', phone='1234567890', shop_name='Shop'
        )
        self.supplier.set_password('pass1234')
        self.supplier.save()

        cat = Category.objects.create(name='Cement', slug='cement')
        self.product = Product.objects.create(
            supplier=self.supplier, category=cat,
            name='Test Cement', description='Good cement',
            price=450.00, stock=100,
        )

    def test_product_list_public(self):
        res = self.client.get('/api/products/')
        self.assertEqual(res.status_code, status.HTTP_200_OK)

    def test_product_slug_autogenerated(self):
        self.assertTrue(len(self.product.slug) > 0)

    def test_product_detail(self):
        res = self.client.get(f'/api/products/{self.product.product_id}/')
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        self.assertEqual(res.data['name'], 'Test Cement')


class CartTest(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.buyer = Buyer(name='Buyer', email='buy@b.com', phone='9876543210')
        self.buyer.set_password('pass1234')
        self.buyer.save()

        self.supplier = Supplier(
            name='Sup', email='s2@s.com', phone='1234567890', shop_name='Shop2'
        )
        self.supplier.set_password('pass1234')
        self.supplier.save()

        cat = Category.objects.create(name='Steel', slug='steel')
        self.product = Product.objects.create(
            supplier=self.supplier, category=cat,
            name='Steel Rod', description='Strong rod',
            price=200.00, stock=50,
        )

        # Login buyer
        res = self.client.post('/api/login/', {'email': 'buy@b.com', 'password': 'pass1234'}, format='json')
        self.token = res.data['access']
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.token}')

    def test_add_to_cart(self):
        res = self.client.post('/api/cart/', {'product': self.product.product_id, 'quantity': 2}, format='json')
        self.assertIn(res.status_code, [status.HTTP_200_OK, status.HTTP_201_CREATED])

    def test_cart_count(self):
        self.client.post('/api/cart/', {'product': self.product.product_id, 'quantity': 1}, format='json')
        res = self.client.get('/api/cart/count/')
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        self.assertIn('count', res.data)